config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :cars do
    resources :bookings, only: [:new, :create]
  end
  resources :users, only: [:show, :edit, :update]
  resources :bookings, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :car

def total
  
end

end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_one_attached :photo
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch::Model
  pg_search_scope :search_by_make_and_model,
    against: [ :make, :model, :address ],
    using: {
      tsearch: { prefix: true } 
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cars
  has_many :bookings
  has_one_attached :photo
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :password, :photo)}
    # devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:email])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def new
    @car = Car.find(params[:car_id])
    @booking = Booking.new
  end

  def create
    @user = current_user
    @car = Car.find(params[:car_id])
    @booking = Booking.new(booking_params)
    @booking.user = @user
    @booking.car = @car
    if @booking.save!
      redirect_to booking_path(@booking)
    else
      render car_path
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end

end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = Car.all
    # the `geocoded` scope filters only flats with coordinates (latitude & longitude)
    markers
    if params[:query].present?
      @cars = Car.all.search_by_make_and_model(params[:query])
      markers
    end
  end

  def show
    @car = Car.find(params[:id])
    @booking = Booking.new
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    @car.user = current_user
    if @car.save
      redirect_to car_path(@car)
    else
      render :new
    end
  end

  def edit
    @car = Car.find(params[:id])
  end

  def update
    @car = Car.find(params[:id])
    @car.update(car_params)
    redirect_to car_path(@car)
  end

  def destroy
    @car = Car.find(params[:id])
    @car.destroy
    redirect_to cars_path
  end

  private

  def markers
    @markers = @cars.geocoded.map do |car|
      {
        lat: car.latitude,
        lng: car.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { car: car }),
      }
    end
  end

  def car_params
    params.require(:car).permit(:make, :model, :year, :seats, :transmission, :description, :price, :photo, :address)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<%= simple_form_for [car, booking] do |f| %>
  <%= f.input :start_date, as: :date, html5: true %>
  <%= f.input :end_date, as: :date, html5: true %>
  <%= f.submit "Add booking", class: "w-100 btn btn-primary rounded" %>
<% end %>

app/views/bookings/new.html.erb
<div class="form-container">
  <h1>My booking</h1>
  <%= simple_form_for [@car, @booking] do |f| %>
    <%= f.input :start_date %>
    <%= f.input :end_date %>
    <%= f.submit "Add booking" %>
  <% end %>
</div>

app/views/bookings/show.html.erb
<div class="form-container">
  <h2> Booking details </h2>
  <hr>
  <p> <strong>Make:</strong> <%= @booking.car.make %> </p>
  <p> <strong>Model:</strong> <%= @booking.car.model %> </p>
  <p> <strong>Year:</strong> <%= @booking.car.year %> </p>

  <p> <strong>Start date:</strong> <%= @booking.start_date %> </p>
  <p> <strong>End date:</strong> <%= @booking.end_date %> </p>
  <p> <strong>Price / day:</strong> <%= @booking.car.price %> </p>

  <p> <strong>Days:</strong> <%= hours = ((@booking.end_date - @booking.start_date) / 3600 / 24).to_i %></p>
  <p><strong>Total:</strong> <%= hours * @booking.car.price %></p>
</div>

app/views/cars/_form.html.erb
<div class="form-container">
  <h1>Car Details</h1>
  <%= simple_form_for @car do |f| %>
    <%= f.input :make %>
    <%= f.input :model %>
    <%= f.input :year %>
    <%= f.input :transmission %>
    <%= f.input :seats %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :address %>
    <%= f.input :photo, as: :file %>
    <div class="d-flex">
      <%= f.submit "Update", class: "btn btn-primary rounded w-100 mr-4" %>
      <%= link_to "Go back", car_path(@car), class: "btn btn-success rounded w-100"  %>
    </div>
    <% end %>
</div>

app/views/cars/_info_window.html.erb
<div class="infopop">
  <h5><%= car.make %> <%= car.model %></h5>
  <h6><%= (car.price).to_i %>kr/day</h6>
  <h6><%= car.address %></h6>
  <%= link_to "Book car", car_path(car), class: "btn btn-primary" %>
</div>
<!-- <p></p> -->

app/views/cars/edit.html.erb
<%= render "form", car: @car %>

app/views/cars/index.html.erb
  <%#= simple_form_for :search, url: cars_path, method: "GET", html: { class: 'form-inline' } do |f| %>
  <%#= f.input_field :make, input_html: {value: ""}, placeholder: 'What car are you looking for?', name: "query" %>
  <%#= f.submit "Search", class: "btn btn-primary" %>
<%# end %>


<div class="car-container pt-3">
  <ul class = "list-unstyled pr-3 pl-3" >
      <%= form_tag cars_path, method: :get do %>
      <div class="input-group mb-4">
      <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "Find a car" %>
      <div class="input-group-append">
      <%= submit_tag "Find car!", class: "btn btn-primary rounded-lg" %>
      </div>
      </div>
      <% end %>

     <% @cars.each do |car| %>

     <li class = "car-card">
      <%= link_to car_path(car), class: "link-unstyled" do %>
      <div class="d-flex">
      <% if car.photo.attached? %>
      <%= cl_image_tag car.photo.key, class: "car-img rounded"  %>
        <% else %>
         <img class="car-img rounded"
        src="https://images.unsplash.com/photo-1603924498829-ce16c0da32aa?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=992&q=80" alt="car photo" >
      <% end %>
        <div class = "car-card-info">
          <div class="">

            <div class="title-heart">
              <h3 class="car-card-title"><%= car.make %> <%= car.model %> <span class="car-card-year"><%= car.year %></span></h3>
              <i class="far fa-heart red-heart"></i>
            </div>
              <span class="car-card-description"><%= car.description %></span>
              <div class="car-card-location"><i class="fas fa-map-pin"></i> <%= car.address %></div>

          </div>
          <div class="car-card-owner">
            <div class="">
              <span class="">Owned by <%= car.user.first_name %></span>
            </div>
            <div class="price-day">
              <span class="price-bold"><%= car.price %></span>
              <span class="">SEK/Day</span>
            </div>
          </div>
        </div>
      </div>
        <% end %>
     </li>

       <% end %>
  </ul>
  <div class="map-container pr-3">
    <div id="map"
        style="width: 100%; height: 600px;"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
</div>

app/views/cars/new.html.erb
<div class="form-container">
  <h1>Car Details</h1>
  <%= simple_form_for @car do |f| %>
    <%= f.input :make %>
    <%= f.input :model %>
    <%= f.input :year %>
    <%= f.input :transmission %>
    <%= f.input :seats %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :address %>
    <%= f.input :photo, as: :file %>
    <div class="d-flex">
      <%= f.submit "Add car", class: "btn btn-primary rounded w-100 mr-4" %>
      <%= link_to "Go back", root_path, class: "btn btn-success rounded w-100"  %>
    </div>
    <% end %>
</div>

app/views/cars/show.html.erb
<div id="carouselExampleControls" class="carousel slide car-carousel" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <% if @car.photo.attached? %>
        <%= cl_image_tag @car.photo.key, class: "d-block w-100"  %>
      <% else %>
         <img src="https://images.unsplash.com/photo-1511407397940-d57f68e81203?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2534&q=80" class="d-block w-100" alt="car photo" >
      <% end %>
    </div>
    <div class="carousel-item">
      <% if @car.photo.attached? %>
        <%= cl_image_tag @car.photo.key, class: "d-block w-100"  %>
      <% else %>
         <img src="https://images.unsplash.com/photo-1511407397940-d57f68e81203?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2534&q=80" class="d-block w-100" alt="car photo" >
      <% end %>
    </div>
    <div class="carousel-item">
      <% if @car.photo.attached? %>
        <%= cl_image_tag @car.photo.key, class: "d-block w-100"  %>
      <% else %>
         <img src="https://images.unsplash.com/photo-1511407397940-d57f68e81203?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2534&q=80" class="d-block w-100" alt="car photo" >
      <% end %>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<div class="show-container">
  <div class="d-flex justify-content-between">

    <div class="full-info">

      <div class="car-brand">
        <h2 class="car-card-title"><%= @car[:make] %> <%= @car[:model] %> <span class=""><%= @car[:year] %></span></h2>
      </div>
      <span class="car-owner">Owned by <%= @car.user[:first_name] %> <%= @car.user[:last_name] %></span>

      <div class="car-description">
        <span class="car-desc"><%= @car[:description] %></span>
      </div>

      <div class="owner-info mt-5 pb-5">
        <% if @car.user.photo.attached? %>
        <%= cl_image_tag @car.user.photo.key, class: "owner-avatar rounded-circle" %>
        <% else %>
        <img src="https://images.unsplash.com/photo-1496345875659-11f7dd282d1d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1650&q=80" alt="" class="owner-avatar rounded-circle">
        <% end %>
        <div class="name-address">
          <span class="car-owner"><strong>Car owned by <%= @car.user[:first_name] %> <%= @car.user[:last_name] %></strong></span>
          <span class="car-owner"><%= @car[:address] %></span>
        </div>
      </div>

      <div class="car-info pb-5">
        <h4>Information about the car</h4>

        <div class="grid-container pt-3">

          <div class="mt-2 about-info">
            <i class="fas fa-car-side icon"></i>
            <div class="minw-0">
              <h6 class="text-nowrap m-0">Brand</h6>
              <span><%= @car[:make] %></span>
            </div>
          </div>

          <div class="mt-2 about-info">
            <i class="fas fa-car icon"></i>
            <div class="minw-0">
              <h6 class="text-nowrap m-0">Model</h6>
              <span><%= @car[:model] %></span>
            </div>
          </div>

          <div class="mt-2 about-info">
            <i class="fas fa-cogs icon"></i>
            <div class="minw-0">
              <h6 class="text-nowrap m-0">Transmission</h6>
              <span><%= @car[:transmission] %></span>
            </div>
          </div>

          <div class="mt-2 about-info">
            <i class="fas fa-chair icon"></i>
            <div class="minw-0">
              <h6 class="text-nowrap m-0">Seats</h6>
              <span><%= @car[:seats] %></span>
            </div>
          </div>

          <div class="mt-2 about-info">
            <i class="fas fa-calendar-alt icon"></i>
            <div class="minw-0">
              <h6 class="text-nowrap m-0">Year</h6>
              <span><%= @car[:year] %></span>
            </div>
          </div>

          <div class="mt-2 about-info">
            <i class="fas fa-dollar-sign icon"></i>
            <div class="minw-0">
              <h6 class="text-nowrap m-0">Price/Day</h6>
              <span><%= @car[:price]  %> SEK</span>
            </div>
          </div>

        </div>
        <%= link_to "Edit your car",  edit_car_path(@car), class: "btn btn-success rounded mt-3"  %>
      </div>

    </div>

    <div class="booking-form">
      <%= render 'bookings/form', {car: @car, booking: Booking.new} %>
      <%= link_to "Go back to all cars",  cars_path, class: "btn btn-success rounded mt-3 w-100"  %>
    </div>

  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aircar</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <div class="page-container">
      <div class="navbar-container"><%= render "shared/navbar" %>
      </div>
      <div class="content-container"><%= yield %>
      </div>
      <div class="footer-container"><%= render "shared/footer" %>
      </div>
    </div>
  </body>
  </html>

app/views/pages/home.html.erb
<div>

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_path "roadcar.jpg"%>);">
  <div class="container wrapheader">
    <h1>Enjoy the freedom of having the right car only when you need one</h1>
  </div>
</div>

<div class="mt-3">



  <h2 class="text-center pb-2 pt-1">How can AirCar work for you?</h2>

  <div class="cards home_card" >

    <div class="card">
      <%= link_to cars_path, class: "link-unstyled" do %>
      <h4>Find the car you need</h4>
      <%= image_tag "happy_renter.jpg", class: "w-100 class pt-1 pb-1"%>
      <p>Rent the car of your dreams</p>
      <% end %>
    </div>
    <div class="card">
      <%= link_to new_car_path, class: "link-unstyled" do %>
      <h4>Rent your car out</h4>
      <%= image_tag "rent_out.jpg", class: "w-100 class pt-1 pb-1"%>
      <p>Make money - be climate smart</p>
      <% end %>
    </div>
    <div class="card">
      <%= link_to new_user_registration_path, class: "link-unstyled" do %>
      <h4>Become an AirCar member</h4>
      <%= image_tag "become_member.jpg", class: "w-100 class pt-1 pb-1"%>
      <p>Create your profile today</p>
      <% end %>
    </div>
  </div>
</div>

</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-copyright">
  © 2020 AirCar | All Rights Reserved
  </div>
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div>
    <%= image_tag "aircar-pos.png", style: 'width: 120px;' %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "aircar-neg.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "See cars", cars_path, class: "nav-link color-white" %>
        </li>
        <li class="nav-item">
          <%= link_to "List your car", new_car_path, class: "nav-link color-white" %>
        </li>
        <li class="nav-item dropdown">
          <% if current_user.photo.attached? %>
          <%= cl_image_tag current_user.photo.key, class: "avatar-large dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item color-blue" %>
          <% else %>
         <img src="https://kitt.lewagon.com/placeholder/users/ssaunier" class="avatar-large dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
         <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
         <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item color-blue" %>
          <% end %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link color-white" %>
        </li>
        <li class="nav-item">
          <%= link_to "Create an account", new_user_registration_path, class: "nav-link color-white" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>